package tables;
// Generated 23 juil. 2013 18:33:26 by Hibernate Tools 3.2.1.GA



/**
 * EbCity generated by hbm2java
 */
public class EbCity  implements java.io.Serializable {


     private Integer idebCity;
     private EbCountry ebCountry;
     private String ebCityName;

    public EbCity() {
    }

    public EbCity(EbCountry ebCountry, String ebCityName) {
       this.ebCountry = ebCountry;
       this.ebCityName = ebCityName;
    }
   
    public Integer getIdebCity() {
        return this.idebCity;
    }
    
    public void setIdebCity(Integer idebCity) {
        this.idebCity = idebCity;
    }
    public EbCountry getEbCountry() {
        return this.ebCountry;
    }
    
    public void setEbCountry(EbCountry ebCountry) {
        this.ebCountry = ebCountry;
    }
    public String getEbCityName() {
        return this.ebCityName;
    }
    
    public void setEbCityName(String ebCityName) {
        this.ebCityName = ebCityName;
    }




}


