package tables;
// Generated 31-juil.-2013 17:30:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EbCountry generated by hbm2java
 */
public class EbCountry  implements java.io.Serializable {


     private Integer idebCountry;
     private String ebCountryName;
     private Set ebCities = new HashSet(0);
     private Set ebClis = new HashSet(0);
     private Set ebTravelfeeses = new HashSet(0);

    public EbCountry() {
    }

	
    public EbCountry(String ebCountryName) {
        this.ebCountryName = ebCountryName;
    }
    public EbCountry(String ebCountryName, Set ebCities, Set ebClis, Set ebTravelfeeses) {
       this.ebCountryName = ebCountryName;
       this.ebCities = ebCities;
       this.ebClis = ebClis;
       this.ebTravelfeeses = ebTravelfeeses;
    }
   
    public Integer getIdebCountry() {
        return this.idebCountry;
    }
    
    public void setIdebCountry(Integer idebCountry) {
        this.idebCountry = idebCountry;
    }
    public String getEbCountryName() {
        return this.ebCountryName;
    }
    
    public void setEbCountryName(String ebCountryName) {
        this.ebCountryName = ebCountryName;
    }
    public Set getEbCities() {
        return this.ebCities;
    }
    
    public void setEbCities(Set ebCities) {
        this.ebCities = ebCities;
    }
    public Set getEbClis() {
        return this.ebClis;
    }
    
    public void setEbClis(Set ebClis) {
        this.ebClis = ebClis;
    }
    public Set getEbTravelfeeses() {
        return this.ebTravelfeeses;
    }
    
    public void setEbTravelfeeses(Set ebTravelfeeses) {
        this.ebTravelfeeses = ebTravelfeeses;
    }




}


