package tables;
// Generated 31-juil.-2013 17:30:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * EbEvents generated by hbm2java
 */
public class EbEvents  implements java.io.Serializable {


     private Integer idebEvent;
     private Employees employees;
     private String ebEventsName;
     private String ebEventsDesc;
     private Date ebEventsStartDate;
     private Date ebEventsEndDate;
     private int ebEventsIdCli;
     private Set ebReleventempdates = new HashSet(0);

    public EbEvents() {
    }

	
    public EbEvents(Date ebEventsStartDate, int ebEventsIdCli) {
        this.ebEventsStartDate = ebEventsStartDate;
        this.ebEventsIdCli = ebEventsIdCli;
    }
    public EbEvents(Employees employees, String ebEventsName, String ebEventsDesc, Date ebEventsStartDate, Date ebEventsEndDate, int ebEventsIdCli, Set ebReleventempdates) {
       this.employees = employees;
       this.ebEventsName = ebEventsName;
       this.ebEventsDesc = ebEventsDesc;
       this.ebEventsStartDate = ebEventsStartDate;
       this.ebEventsEndDate = ebEventsEndDate;
       this.ebEventsIdCli = ebEventsIdCli;
       this.ebReleventempdates = ebReleventempdates;
    }
   
    public Integer getIdebEvent() {
        return this.idebEvent;
    }
    
    public void setIdebEvent(Integer idebEvent) {
        this.idebEvent = idebEvent;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getEbEventsName() {
        return this.ebEventsName;
    }
    
    public void setEbEventsName(String ebEventsName) {
        this.ebEventsName = ebEventsName;
    }
    public String getEbEventsDesc() {
        return this.ebEventsDesc;
    }
    
    public void setEbEventsDesc(String ebEventsDesc) {
        this.ebEventsDesc = ebEventsDesc;
    }
    public Date getEbEventsStartDate() {
        return this.ebEventsStartDate;
    }
    
    public void setEbEventsStartDate(Date ebEventsStartDate) {
        this.ebEventsStartDate = ebEventsStartDate;
    }
    public Date getEbEventsEndDate() {
        return this.ebEventsEndDate;
    }
    
    public void setEbEventsEndDate(Date ebEventsEndDate) {
        this.ebEventsEndDate = ebEventsEndDate;
    }
    public int getEbEventsIdCli() {
        return this.ebEventsIdCli;
    }
    
    public void setEbEventsIdCli(int ebEventsIdCli) {
        this.ebEventsIdCli = ebEventsIdCli;
    }
    public Set getEbReleventempdates() {
        return this.ebReleventempdates;
    }
    
    public void setEbReleventempdates(Set ebReleventempdates) {
        this.ebReleventempdates = ebReleventempdates;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 17 * hash + Objects.hashCode(this.idebEvent);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EbEvents other = (EbEvents) obj;
        if (!Objects.equals(this.idebEvent, other.idebEvent)) {
            return false;
        }
        if (!Objects.equals(this.employees, other.employees)) {
            return false;
        }
        if (!Objects.equals(this.ebEventsDesc, other.ebEventsDesc)) {
            return false;
        }
        if (!Objects.equals(this.ebEventsStartDate, other.ebEventsStartDate)) {
            return false;
        }
        if (!Objects.equals(this.ebEventsEndDate, other.ebEventsEndDate)) {
            return false;
        }
        if (this.ebEventsIdCli != other.ebEventsIdCli) {
            return false;
        }
        return true;
    }




}


