package tables;
// Generated 16 juil. 2013 22:43:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EbEvents generated by hbm2java
 */
public class EbEvents  implements java.io.Serializable {


     private Integer idebEvent;
     private String ebEventsName;
     private String ebEventsDesc;
     private Date ebEventsStartDate;
     private Date ebEventsEndDate;
     private int ebEventsIdCli;
     private Set ebRelempevents = new HashSet(0);

    public EbEvents() {
    }

	
    public EbEvents(Date ebEventsStartDate, int ebEventsIdCli) {
        this.ebEventsStartDate = ebEventsStartDate;
        this.ebEventsIdCli = ebEventsIdCli;
    }
    public EbEvents(String ebEventsName, String ebEventsDesc, Date ebEventsStartDate, Date ebEventsEndDate, int ebEventsIdCli, Set ebRelempevents) {
       this.ebEventsName = ebEventsName;
       this.ebEventsDesc = ebEventsDesc;
       this.ebEventsStartDate = ebEventsStartDate;
       this.ebEventsEndDate = ebEventsEndDate;
       this.ebEventsIdCli = ebEventsIdCli;
       this.ebRelempevents = ebRelempevents;
    }
   
    public Integer getIdebEvent() {
        return this.idebEvent;
    }
    
    public void setIdebEvent(Integer idebEvent) {
        this.idebEvent = idebEvent;
    }
    public String getEbEventsName() {
        return this.ebEventsName;
    }
    
    public void setEbEventsName(String ebEventsName) {
        this.ebEventsName = ebEventsName;
    }
    public String getEbEventsDesc() {
        return this.ebEventsDesc;
    }
    
    public void setEbEventsDesc(String ebEventsDesc) {
        this.ebEventsDesc = ebEventsDesc;
    }
    public Date getEbEventsStartDate() {
        return this.ebEventsStartDate;
    }
    
    public void setEbEventsStartDate(Date ebEventsStartDate) {
        this.ebEventsStartDate = ebEventsStartDate;
    }
    public Date getEbEventsEndDate() {
        return this.ebEventsEndDate;
    }
    
    public void setEbEventsEndDate(Date ebEventsEndDate) {
        this.ebEventsEndDate = ebEventsEndDate;
    }
    public int getEbEventsIdCli() {
        return this.ebEventsIdCli;
    }
    
    public void setEbEventsIdCli(int ebEventsIdCli) {
        this.ebEventsIdCli = ebEventsIdCli;
    }
    public Set getEbRelempevents() {
        return this.ebRelempevents;
    }
    
    public void setEbRelempevents(Set ebRelempevents) {
        this.ebRelempevents = ebRelempevents;
    }




}


