package tables;
// Generated 18-juil.-2013 11:41:10 by Hibernate Tools 3.2.1.GA



/**
 * EbReleventempdateId generated by hbm2java
 */
public class EbReleventempdateId  implements java.io.Serializable {


     private int idebRelEventEmpDate;
     private int ebRelEventEmpDateEventId;
     private int ebRelEventEmpDateEmployee;

    public EbReleventempdateId() {
    }

    public EbReleventempdateId(int idebRelEventEmpDate, int ebRelEventEmpDateEventId, int ebRelEventEmpDateEmployee) {
       this.idebRelEventEmpDate = idebRelEventEmpDate;
       this.ebRelEventEmpDateEventId = ebRelEventEmpDateEventId;
       this.ebRelEventEmpDateEmployee = ebRelEventEmpDateEmployee;
    }
   
    public int getIdebRelEventEmpDate() {
        return this.idebRelEventEmpDate;
    }
    
    public void setIdebRelEventEmpDate(int idebRelEventEmpDate) {
        this.idebRelEventEmpDate = idebRelEventEmpDate;
    }
    public int getEbRelEventEmpDateEventId() {
        return this.ebRelEventEmpDateEventId;
    }
    
    public void setEbRelEventEmpDateEventId(int ebRelEventEmpDateEventId) {
        this.ebRelEventEmpDateEventId = ebRelEventEmpDateEventId;
    }
    public int getEbRelEventEmpDateEmployee() {
        return this.ebRelEventEmpDateEmployee;
    }
    
    public void setEbRelEventEmpDateEmployee(int ebRelEventEmpDateEmployee) {
        this.ebRelEventEmpDateEmployee = ebRelEventEmpDateEmployee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EbReleventempdateId) ) return false;
		 EbReleventempdateId castOther = ( EbReleventempdateId ) other; 
         
		 return (this.getIdebRelEventEmpDate()==castOther.getIdebRelEventEmpDate())
 && (this.getEbRelEventEmpDateEventId()==castOther.getEbRelEventEmpDateEventId())
 && (this.getEbRelEventEmpDateEmployee()==castOther.getEbRelEventEmpDateEmployee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdebRelEventEmpDate();
         result = 37 * result + this.getEbRelEventEmpDateEventId();
         result = 37 * result + this.getEbRelEventEmpDateEmployee();
         return result;
   }   


}


