package tables;
// Generated 16 juil. 2013 22:43:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EbReleventempdate generated by hbm2java
 */
public class EbReleventempdate  implements java.io.Serializable {


     private EbReleventempdateId id;
     private Date ebRelEventEmpDateStart;
     private Date ebRelEventEmpDateEnd;

    public EbReleventempdate() {
    }

    public EbReleventempdate(EbReleventempdateId id, Date ebRelEventEmpDateStart, Date ebRelEventEmpDateEnd) {
       this.id = id;
       this.ebRelEventEmpDateStart = ebRelEventEmpDateStart;
       this.ebRelEventEmpDateEnd = ebRelEventEmpDateEnd;
    }
   
    public EbReleventempdateId getId() {
        return this.id;
    }
    
    public void setId(EbReleventempdateId id) {
        this.id = id;
    }
    public Date getEbRelEventEmpDateStart() {
        return this.ebRelEventEmpDateStart;
    }
    
    public void setEbRelEventEmpDateStart(Date ebRelEventEmpDateStart) {
        this.ebRelEventEmpDateStart = ebRelEventEmpDateStart;
    }
    public Date getEbRelEventEmpDateEnd() {
        return this.ebRelEventEmpDateEnd;
    }
    
    public void setEbRelEventEmpDateEnd(Date ebRelEventEmpDateEnd) {
        this.ebRelEventEmpDateEnd = ebRelEventEmpDateEnd;
    }




}


