package tables;
// Generated 16 juil. 2013 22:43:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EbRelempevent generated by hbm2java
 */
public class EbRelempevent  implements java.io.Serializable {


     private EbRelempeventId id;
     private Employees employees;
     private EbEvents ebEvents;
     private Date ebRelEmpEventStart;
     private Date ebRelEmpEventEnd;
     private boolean ebRelEmpEventEmpTimeValidation;
     private boolean ebRelEmpEventAdminTimeValidation;

    public EbRelempevent() {
    }

    public EbRelempevent(EbRelempeventId id, Employees employees, EbEvents ebEvents, Date ebRelEmpEventStart, Date ebRelEmpEventEnd, boolean ebRelEmpEventEmpTimeValidation, boolean ebRelEmpEventAdminTimeValidation) {
       this.id = id;
       this.employees = employees;
       this.ebEvents = ebEvents;
       this.ebRelEmpEventStart = ebRelEmpEventStart;
       this.ebRelEmpEventEnd = ebRelEmpEventEnd;
       this.ebRelEmpEventEmpTimeValidation = ebRelEmpEventEmpTimeValidation;
       this.ebRelEmpEventAdminTimeValidation = ebRelEmpEventAdminTimeValidation;
    }
   
    public EbRelempeventId getId() {
        return this.id;
    }
    
    public void setId(EbRelempeventId id) {
        this.id = id;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public EbEvents getEbEvents() {
        return this.ebEvents;
    }
    
    public void setEbEvents(EbEvents ebEvents) {
        this.ebEvents = ebEvents;
    }
    public Date getEbRelEmpEventStart() {
        return this.ebRelEmpEventStart;
    }
    
    public void setEbRelEmpEventStart(Date ebRelEmpEventStart) {
        this.ebRelEmpEventStart = ebRelEmpEventStart;
    }
    public Date getEbRelEmpEventEnd() {
        return this.ebRelEmpEventEnd;
    }
    
    public void setEbRelEmpEventEnd(Date ebRelEmpEventEnd) {
        this.ebRelEmpEventEnd = ebRelEmpEventEnd;
    }
    public boolean isEbRelEmpEventEmpTimeValidation() {
        return this.ebRelEmpEventEmpTimeValidation;
    }
    
    public void setEbRelEmpEventEmpTimeValidation(boolean ebRelEmpEventEmpTimeValidation) {
        this.ebRelEmpEventEmpTimeValidation = ebRelEmpEventEmpTimeValidation;
    }
    public boolean isEbRelEmpEventAdminTimeValidation() {
        return this.ebRelEmpEventAdminTimeValidation;
    }
    
    public void setEbRelEmpEventAdminTimeValidation(boolean ebRelEmpEventAdminTimeValidation) {
        this.ebRelEmpEventAdminTimeValidation = ebRelEmpEventAdminTimeValidation;
    }




}


