package tables;
// Generated 31-juil.-2013 17:30:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EbReleventempdate generated by hbm2java
 */
public class EbReleventempdate  implements java.io.Serializable {


     private Integer idebRelEventEmpDate;
     private Employees employees;
     private EbEvents ebEvents;
     private Date ebRelEventEmpDateStart;
     private Date ebRelEventEmpDateEnd;
     private Date ebRelEventEmpDateDate;
     private Integer ebRelEventEmpDateTrajetMinute;
     private Integer ebRelEventEmpDateLunchMinutes;
     private String ebRelEventEmpDateJobDesc;
     private boolean ebRelEventEmpDateUserTimeValid;
     private boolean ebRelEventEmpDateAdminTimeValid;
     private boolean ebRelEventEmpDateFullDay;

    public EbReleventempdate() {
    }

	
    public EbReleventempdate(Employees employees, EbEvents ebEvents, Date ebRelEventEmpDateStart, Date ebRelEventEmpDateEnd, boolean ebRelEventEmpDateUserTimeValid, boolean ebRelEventEmpDateAdminTimeValid, boolean ebRelEventEmpDateFullDay) {
        this.employees = employees;
        this.ebEvents = ebEvents;
        this.ebRelEventEmpDateStart = ebRelEventEmpDateStart;
        this.ebRelEventEmpDateEnd = ebRelEventEmpDateEnd;
        this.ebRelEventEmpDateUserTimeValid = ebRelEventEmpDateUserTimeValid;
        this.ebRelEventEmpDateAdminTimeValid = ebRelEventEmpDateAdminTimeValid;
        this.ebRelEventEmpDateFullDay = ebRelEventEmpDateFullDay;
    }
    public EbReleventempdate(Employees employees, EbEvents ebEvents, Date ebRelEventEmpDateStart, Date ebRelEventEmpDateEnd, Date ebRelEventEmpDateDate, Integer ebRelEventEmpDateTrajetMinute, Integer ebRelEventEmpDateLunchMinutes, String ebRelEventEmpDateJobDesc, boolean ebRelEventEmpDateUserTimeValid, boolean ebRelEventEmpDateAdminTimeValid, boolean ebRelEventEmpDateFullDay) {
       this.employees = employees;
       this.ebEvents = ebEvents;
       this.ebRelEventEmpDateStart = ebRelEventEmpDateStart;
       this.ebRelEventEmpDateEnd = ebRelEventEmpDateEnd;
       this.ebRelEventEmpDateDate = ebRelEventEmpDateDate;
       this.ebRelEventEmpDateTrajetMinute = ebRelEventEmpDateTrajetMinute;
       this.ebRelEventEmpDateLunchMinutes = ebRelEventEmpDateLunchMinutes;
       this.ebRelEventEmpDateJobDesc = ebRelEventEmpDateJobDesc;
       this.ebRelEventEmpDateUserTimeValid = ebRelEventEmpDateUserTimeValid;
       this.ebRelEventEmpDateAdminTimeValid = ebRelEventEmpDateAdminTimeValid;
       this.ebRelEventEmpDateFullDay = ebRelEventEmpDateFullDay;
    }
   
    public Integer getIdebRelEventEmpDate() {
        return this.idebRelEventEmpDate;
    }
    
    public void setIdebRelEventEmpDate(Integer idebRelEventEmpDate) {
        this.idebRelEventEmpDate = idebRelEventEmpDate;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public EbEvents getEbEvents() {
        return this.ebEvents;
    }
    
    public void setEbEvents(EbEvents ebEvents) {
        this.ebEvents = ebEvents;
    }
    public Date getEbRelEventEmpDateStart() {
        return this.ebRelEventEmpDateStart;
    }
    
    public void setEbRelEventEmpDateStart(Date ebRelEventEmpDateStart) {
        this.ebRelEventEmpDateStart = ebRelEventEmpDateStart;
    }
    public Date getEbRelEventEmpDateEnd() {
        return this.ebRelEventEmpDateEnd;
    }
    
    public void setEbRelEventEmpDateEnd(Date ebRelEventEmpDateEnd) {
        this.ebRelEventEmpDateEnd = ebRelEventEmpDateEnd;
    }
    public Date getEbRelEventEmpDateDate() {
        return this.ebRelEventEmpDateDate;
    }
    
    public void setEbRelEventEmpDateDate(Date ebRelEventEmpDateDate) {
        this.ebRelEventEmpDateDate = ebRelEventEmpDateDate;
    }
    public Integer getEbRelEventEmpDateTrajetMinute() {
        return this.ebRelEventEmpDateTrajetMinute;
    }
    
    public void setEbRelEventEmpDateTrajetMinute(Integer ebRelEventEmpDateTrajetMinute) {
        this.ebRelEventEmpDateTrajetMinute = ebRelEventEmpDateTrajetMinute;
    }
    public Integer getEbRelEventEmpDateLunchMinutes() {
        return this.ebRelEventEmpDateLunchMinutes;
    }
    
    public void setEbRelEventEmpDateLunchMinutes(Integer ebRelEventEmpDateLunchMinutes) {
        this.ebRelEventEmpDateLunchMinutes = ebRelEventEmpDateLunchMinutes;
    }
    public String getEbRelEventEmpDateJobDesc() {
        return this.ebRelEventEmpDateJobDesc;
    }
    
    public void setEbRelEventEmpDateJobDesc(String ebRelEventEmpDateJobDesc) {
        this.ebRelEventEmpDateJobDesc = ebRelEventEmpDateJobDesc;
    }
    public boolean isEbRelEventEmpDateUserTimeValid() {
        return this.ebRelEventEmpDateUserTimeValid;
    }
    
    public void setEbRelEventEmpDateUserTimeValid(boolean ebRelEventEmpDateUserTimeValid) {
        this.ebRelEventEmpDateUserTimeValid = ebRelEventEmpDateUserTimeValid;
    }
    public boolean isEbRelEventEmpDateAdminTimeValid() {
        return this.ebRelEventEmpDateAdminTimeValid;
    }
    
    public void setEbRelEventEmpDateAdminTimeValid(boolean ebRelEventEmpDateAdminTimeValid) {
        this.ebRelEventEmpDateAdminTimeValid = ebRelEventEmpDateAdminTimeValid;
    }
    public boolean isEbRelEventEmpDateFullDay() {
        return this.ebRelEventEmpDateFullDay;
    }
    
    public void setEbRelEventEmpDateFullDay(boolean ebRelEventEmpDateFullDay) {
        this.ebRelEventEmpDateFullDay = ebRelEventEmpDateFullDay;
    }




}


