package tables;
// Generated 23 juil. 2013 18:33:26 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EbWorktimetable generated by hbm2java
 */
public class EbWorktimetable  implements java.io.Serializable {


     private Integer idworkTimeTable;
     private Employees employees;
     private Date ebWorkTimeTableDate;
     private int ebWorkTimeTableNbHours;
     private boolean ebWorkTimeTableAdminValidation;
     private int ebWorkTimeTableNbMin;
     private boolean ebWorkTimeTableUserValidation;
     private Date ebWorkTimeTableWeekYear;

    public EbWorktimetable() {
    }

	
    public EbWorktimetable(Employees employees, Date ebWorkTimeTableDate, int ebWorkTimeTableNbHours, boolean ebWorkTimeTableAdminValidation, int ebWorkTimeTableNbMin, boolean ebWorkTimeTableUserValidation) {
        this.employees = employees;
        this.ebWorkTimeTableDate = ebWorkTimeTableDate;
        this.ebWorkTimeTableNbHours = ebWorkTimeTableNbHours;
        this.ebWorkTimeTableAdminValidation = ebWorkTimeTableAdminValidation;
        this.ebWorkTimeTableNbMin = ebWorkTimeTableNbMin;
        this.ebWorkTimeTableUserValidation = ebWorkTimeTableUserValidation;
    }
    public EbWorktimetable(Employees employees, Date ebWorkTimeTableDate, int ebWorkTimeTableNbHours, boolean ebWorkTimeTableAdminValidation, int ebWorkTimeTableNbMin, boolean ebWorkTimeTableUserValidation, Date ebWorkTimeTableWeekYear) {
       this.employees = employees;
       this.ebWorkTimeTableDate = ebWorkTimeTableDate;
       this.ebWorkTimeTableNbHours = ebWorkTimeTableNbHours;
       this.ebWorkTimeTableAdminValidation = ebWorkTimeTableAdminValidation;
       this.ebWorkTimeTableNbMin = ebWorkTimeTableNbMin;
       this.ebWorkTimeTableUserValidation = ebWorkTimeTableUserValidation;
       this.ebWorkTimeTableWeekYear = ebWorkTimeTableWeekYear;
    }
   
    public Integer getIdworkTimeTable() {
        return this.idworkTimeTable;
    }
    
    public void setIdworkTimeTable(Integer idworkTimeTable) {
        this.idworkTimeTable = idworkTimeTable;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Date getEbWorkTimeTableDate() {
        return this.ebWorkTimeTableDate;
    }
    
    public void setEbWorkTimeTableDate(Date ebWorkTimeTableDate) {
        this.ebWorkTimeTableDate = ebWorkTimeTableDate;
    }
    public int getEbWorkTimeTableNbHours() {
        return this.ebWorkTimeTableNbHours;
    }
    
    public void setEbWorkTimeTableNbHours(int ebWorkTimeTableNbHours) {
        this.ebWorkTimeTableNbHours = ebWorkTimeTableNbHours;
    }
    public boolean isEbWorkTimeTableAdminValidation() {
        return this.ebWorkTimeTableAdminValidation;
    }
    
    public void setEbWorkTimeTableAdminValidation(boolean ebWorkTimeTableAdminValidation) {
        this.ebWorkTimeTableAdminValidation = ebWorkTimeTableAdminValidation;
    }
    public int getEbWorkTimeTableNbMin() {
        return this.ebWorkTimeTableNbMin;
    }
    
    public void setEbWorkTimeTableNbMin(int ebWorkTimeTableNbMin) {
        this.ebWorkTimeTableNbMin = ebWorkTimeTableNbMin;
    }
    public boolean isEbWorkTimeTableUserValidation() {
        return this.ebWorkTimeTableUserValidation;
    }
    
    public void setEbWorkTimeTableUserValidation(boolean ebWorkTimeTableUserValidation) {
        this.ebWorkTimeTableUserValidation = ebWorkTimeTableUserValidation;
    }
    public Date getEbWorkTimeTableWeekYear() {
        return this.ebWorkTimeTableWeekYear;
    }
    
    public void setEbWorkTimeTableWeekYear(Date ebWorkTimeTableWeekYear) {
        this.ebWorkTimeTableWeekYear = ebWorkTimeTableWeekYear;
    }




}


