package tables;
// Generated 22-juil.-2013 9:26:48 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Typeclient generated by hbm2java
 */
public class Typeclient  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set ebClis = new HashSet(0);

    public Typeclient() {
    }

	
    public Typeclient(String name) {
        this.name = name;
    }
    public Typeclient(String name, Set ebClis) {
       this.name = name;
       this.ebClis = ebClis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getEbClis() {
        return this.ebClis;
    }
    
    public void setEbClis(Set ebClis) {
        this.ebClis = ebClis;
    }




}


