/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author jsmaya
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        agendaEvent3 = new beans.AgendaEvent();
        jSeparator2 = new javax.swing.JSeparator();
        agendaEvent1 = new beans.AgendaEvent();
        jSeparator3 = new javax.swing.JSeparator();
        agendaEvent2 = new beans.AgendaEvent();
        jSeparator4 = new javax.swing.JSeparator();
        agendaEvent4 = new beans.AgendaEvent();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        agendaDay1 = new beans.AgendaDay();

        setLayout(new java.awt.GridLayout(0, 2));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Blabla");
        jPanel1.add(jLabel1);

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel1.add(jSeparator1);
        jPanel1.add(agendaEvent3);
        jPanel1.add(jSeparator2);
        jPanel1.add(agendaEvent1);
        jPanel1.add(jSeparator3);
        jPanel1.add(agendaEvent2);
        jPanel1.add(jSeparator4);
        jPanel1.add(agendaEvent4);

        jButton1.setText("jButton1");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);

        add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(agendaDay1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beans.AgendaDay agendaDay1;
    private beans.AgendaEvent agendaEvent1;
    private beans.AgendaEvent agendaEvent2;
    private beans.AgendaEvent agendaEvent3;
    private beans.AgendaEvent agendaEvent4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
