/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import beans.AgendaPanel;
import com.toedter.calendar.JCalendar;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author jsmaya
 */
public class TestApplet extends javax.swing.JApplet {

    private AgendaPanel agenda;
    private JCalendar jcalendar;
    private Calendar startCalendar, endCalendar;
    /**
     * Initializes the applet TestApplet
     */
    @Override
    public void init() {
        this.setSize(java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().
                getMaximumWindowBounds().width-16, java.awt.GraphicsEnvironment.
                        getLocalGraphicsEnvironment().getMaximumWindowBounds().
                        height-64);
//        Calendar test = Calendar.getInstance();
//        test.set(2012, 12, 25);
//        for(int i =0; i<1000; i++){
//            test.add(Calendar.DAY_OF_MONTH, 1);
//            System.out.println(test.get(Calendar.DAY_OF_YEAR));
//        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    initAgenda();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void initAgenda(){
//        if(agenda!=null)this.contentPanel.remove(agenda);
        Calendar startTimeElapsed = Calendar.getInstance();
        startCalendar = startDateChooser.getCalendar();
        endCalendar = endDateChooser.getCalendar();
        if(startCalendar == null){
            startCalendar = Calendar.getInstance();
        }
        if(endCalendar == null){
            endCalendar = Calendar.getInstance();
        }
        agenda = new AgendaPanel(startCalendar, endCalendar);
        contentScrollPane.setViewportView(agenda);
//        System.out.println(startCalendar.get(Calendar.WEEK_OF_YEAR));
        this.revalidate();
        Calendar timeElapsed = Calendar.getInstance();
        long millisec =  timeElapsed.getTimeInMillis()-startTimeElapsed.getTimeInMillis();
        lbTitle.setText("Eurobrevets "+millisec);
    }
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelStartDate = new javax.swing.JTextField();
        btJCalStart = new javax.swing.JButton();
        labelEndDate = new javax.swing.JTextField();
        btJCalEnd = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        btBuild = new javax.swing.JButton();
        datePanel = new javax.swing.JPanel();
        startDatePanel = new javax.swing.JPanel();
        lbStartDate = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        endDatePanel = new javax.swing.JPanel();
        lbEndDate = new javax.swing.JLabel();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        contentPanel = new javax.swing.JPanel();
        contentScrollPane = new javax.swing.JScrollPane();

        labelStartDate.setColumns(8);

        btJCalStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toedter/calendar/images/JCalendarColor16.gif"))); // NOI18N
        btJCalStart.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btJCalStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJCalStartActionPerformed(evt);
            }
        });

        labelEndDate.setColumns(8);

        btJCalEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toedter/calendar/images/JCalendarColor16.gif"))); // NOI18N
        btJCalEnd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btJCalEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJCalEndActionPerformed(evt);
            }
        });

        getContentPane().setLayout(new java.awt.GridBagLayout());

        topPanel.setLayout(new java.awt.GridBagLayout());

        lbTitle.setText("Eurobrevets");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        topPanel.add(lbTitle, gridBagConstraints);

        btBuild.setText("Build");
        btBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuildActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        topPanel.add(btBuild, gridBagConstraints);

        datePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbStartDate.setText("startDate");
        startDatePanel.add(lbStartDate);
        startDatePanel.add(startDateChooser);

        datePanel.add(startDatePanel);

        lbEndDate.setText("endDate");
        endDatePanel.add(lbEndDate);
        endDatePanel.add(endDateChooser);

        datePanel.add(endDatePanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        topPanel.add(datePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(topPanel, gridBagConstraints);

        contentPanel.setLayout(new java.awt.GridLayout(1, 7));
        contentPanel.add(contentScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(contentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuildActionPerformed
        initAgenda();
    }//GEN-LAST:event_btBuildActionPerformed

    private void btJCalEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJCalEndActionPerformed
        jcalendar = new JCalendar();
        if(JOptionPane.showOptionDialog(btJCalEnd, jcalendar, "Select a date",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, null, null) == 0){
        labelEndDate.setText(jcalendar.getCalendar()
            .get(Calendar.DAY_OF_MONTH)+"-"+(jcalendar.getCalendar()
                .get(Calendar.MONTH)+1)+"-"+jcalendar.getCalendar()
            .get(Calendar.YEAR));
        endCalendar = jcalendar.getCalendar();
        }
    }//GEN-LAST:event_btJCalEndActionPerformed

    private void btJCalStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJCalStartActionPerformed
        jcalendar = new JCalendar();
        if(JOptionPane.showOptionDialog(btJCalStart, jcalendar, "Select a date",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, null, null) == 0){
        labelStartDate.setText(jcalendar.getCalendar()
            .get(Calendar.DAY_OF_MONTH)+"-"+(jcalendar.getCalendar()
                .get(Calendar.MONTH)+1)+"-"+jcalendar.getCalendar()
            .get(Calendar.YEAR));
        startCalendar = jcalendar.getCalendar();
        }
    }//GEN-LAST:event_btJCalStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuild;
    private javax.swing.JButton btJCalEnd;
    private javax.swing.JButton btJCalStart;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JPanel datePanel;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JPanel endDatePanel;
    private javax.swing.JTextField labelEndDate;
    private javax.swing.JTextField labelStartDate;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbTitle;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JPanel startDatePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
