/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author MpUser
 */
public class AgendaNewEvent extends javax.swing.JPanel {
    
    private List<AgendaUser> userList;
    private List<JCheckBox> userCheckBoxes;
    
    /**
     * Creates new form AgendaNewEventPanel
     */
    public AgendaNewEvent() {
        userCheckBoxes = new ArrayList();
        initComponents();
    }

    public AgendaNewEvent(List<AgendaUser> userList) {
        this.userList = userList;
        userCheckBoxes = new ArrayList();
        initComponents();
        PopulateUsers();
        System.out.println("created");
    }
    
    private void PopulateUsers(){
        System.out.println(userList.size());
        for(AgendaUser user : userList){
            JCheckBox ckb = new JCheckBox();
            ckb.setText(user.getUserName());
            userCheckBoxes.add(ckb);
        }
        System.out.println(userCheckBoxes.size());
        for(JCheckBox ckb : userCheckBoxes){
            this.userPanel.add(ckb);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        title = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateTimeBean3 = new beans.DateTimeBean();
        jLabel3 = new javax.swing.JLabel();
        dateTimeBean4 = new beans.DateTimeBean();
        jLabel5 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        title.setText("Nouvel évènement");
        add(title, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Titre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        contentPanel.add(jLabel1, gridBagConstraints);

        jTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        contentPanel.add(jTextField1, gridBagConstraints);

        jLabel2.setText("De");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        contentPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        contentPanel.add(dateTimeBean3, gridBagConstraints);

        jLabel3.setText("à");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        contentPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        contentPanel.add(dateTimeBean4, gridBagConstraints);

        jLabel5.setText("Participants");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        contentPanel.add(jLabel5, gridBagConstraints);

        userPanel.setLayout(new java.awt.GridLayout(0, 8));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        contentPanel.add(userPanel, gridBagConstraints);

        jLabel4.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        contentPanel.add(jLabel4, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        contentPanel.add(jScrollPane1, gridBagConstraints);

        add(contentPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Créer");
        jButton1.setMaximumSize(new java.awt.Dimension(69, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(69, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(69, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        buttonPanel.add(jButton1, gridBagConstraints);

        jButton2.setText("Annuler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        buttonPanel.add(jButton2, gridBagConstraints);

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel contentPanel;
    private beans.DateTimeBean dateTimeBean3;
    private beans.DateTimeBean dateTimeBean4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel title;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
