/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.Calendar;
import javax.swing.JPanel;

/**
 *
 * @author MpUser
 */
public class DateTimeBean extends JPanel {

    private Calendar dateTime;
    public static final String PROP_DATETIME = "dateTime";

    /**
     * Get the value of dateTime
     *
     * @return the value of dateTime
     */
    public Calendar getDateTime() {
        return dateTime;
    }

    /**
     * Set the value of dateTime
     *
     * @param dateTime new value of dateTime
     */
    public void setDateTime(Calendar dateTime) {
        Calendar oldDateTime = this.dateTime;
        this.dateTime = dateTime;
        this.jDateChooser1.setCalendar(dateTime);
        this.timeComboBox2.setSelectedItem(new TimeHourMinute
                (dateTime.get(Calendar.HOUR_OF_DAY),
                dateTime.get(Calendar.MINUTE)));
        propertyChangeSupport.firePropertyChange
                (PROP_DATETIME, oldDateTime, dateTime);
    }
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    /**
     * Creates new form DateTimeBean
     */
    public DateTimeBean() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        timeComboBox2 = new beans.TimeComboBox();

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        add(jDateChooser1);

        timeComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                timeComboBox2PropertyChange(evt);
            }
        });
        add(timeComboBox2);
    }// </editor-fold>//GEN-END:initComponents

    private void mergeDateTime(){
        TimeHourMinute thm;
        Calendar calendar = this.jDateChooser1.getCalendar();
        if(calendar !=null){
            thm = (TimeHourMinute) this.timeComboBox2.getSelectedItem();
            calendar.set(Calendar.HOUR_OF_DAY, thm.getHour());
            calendar.set(Calendar.MINUTE, thm.getMinute());
            calendar.set(Calendar.SECOND, 0);
            this.setDateTime(calendar);
        }
    }
    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        mergeDateTime();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void timeComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_timeComboBox2PropertyChange
        mergeDateTime();
    }//GEN-LAST:event_timeComboBox2PropertyChange

    @Override
    public void setEnabled(boolean bool){
        this.jDateChooser1.setEnabled(bool);
        this.timeComboBox2.setEnabled(bool);
    }
    
    public void setDateEnabled(boolean bool){
        this.jDateChooser1.setEnabled(bool);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private beans.TimeComboBox timeComboBox2;
    // End of variables declaration//GEN-END:variables
}
