/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

import java.awt.event.FocusEvent;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicComboBoxEditor;


/**
 *
 * @author MpUser
 */
public class TimeComboBox extends JComboBox {

    /**
     * Creates new form TimeComboBox
     */
    public TimeComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEditable(true);
        setMaximumRowCount(7);
        setModel(new javax.swing.DefaultComboBoxModel(newModel()));
        setEditor(new MyBasicEditor());
        setMinimumSize(new java.awt.Dimension(80, 22));
        setPreferredSize(new java.awt.Dimension(80, 22));
    }// </editor-fold>//GEN-END:initComponents
    private TimeHourMinute[] newModel(){
       TimeHourMinute[] thmArray;
       thmArray = new TimeHourMinute[48];
       for(int i = 0; i<48; i+=2){
           TimeHourMinute thm = new TimeHourMinute(i/2);
           TimeHourMinute thm2 = new TimeHourMinute(i/2, 30);
           thmArray[i] = thm;
           thmArray[i+1]=thm2;
       }
       return thmArray;
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void setSelectedItem(Object o) {
        if(o instanceof java.util.Date){
            java.util.Date date = (java.util.Date) o;
            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            TimeHourMinute thm = new TimeHourMinute
                    ((cal.get(Calendar.HOUR_OF_DAY)),cal.get(Calendar.MINUTE));
            super.setSelectedItem(thm);
        }
        super.setSelectedItem(o); //To change body of generated methods, choose Tools | Templates.
    }

}
class MyBasicEditor extends BasicComboBoxEditor{
    Object newValue;
    Object oldValue;
    
    @Override
    public void setItem(Object o) {        
        
        if(o instanceof String){
            TimeHourMinute thm = new TimeHourMinute();
            try{
                String str = (String) o;
                String [] strTab;
                strTab = str.split(":");
                thm.setHour(Integer.parseInt(strTab[0]));
                thm.setMinute(Integer.parseInt(strTab[1]));
                super.setItem(thm);
            }catch(Exception e){
                System.err.println("Problème de casting d'heure");
            }
        }else{
            super.setItem(o);
        }
    }

    @Override
    public void focusLost(FocusEvent fe) {
        super.focusLost(fe); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
